#!/usr/bin/env node
'use strict';

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const os = require('os');
const https = require('https');
const { execSync } = require('child_process');

// ── Colours ──────────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
};

const ok   = (msg) => console.log(`  ${C.green}✓${C.reset} ${msg}`);
const info = (msg) => console.log(`  ${C.blue}ℹ${C.reset} ${msg}`);
const warn = (msg) => console.log(`  ${C.yellow}⚠${C.reset}  ${msg}`);
const err  = (msg) => console.log(`  ${C.red}✗${C.reset} ${msg}`);
const step = (msg) => console.log(`\n${C.bold}${C.cyan}${msg}${C.reset}`);

// ── Readline helpers ──────────────────────────────────────────────────────────
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultVal) {
  return new Promise((resolve) => {
    const hint = defaultVal ? ` ${C.dim}(${defaultVal})${C.reset}` : '';
    rl.question(`  ${C.bold}?${C.reset} ${question}${hint}: `, (ans) => {
      const val = ans.trim() || defaultVal || '';
      resolve(val);
    });
  });
}

function askYN(question, defaultYes = true) {
  return new Promise((resolve) => {
    const hint = defaultYes ? ' [Y/n]' : ' [y/N]';
    rl.question(`  ${C.bold}?${C.reset} ${question}${C.dim}${hint}${C.reset}: `, (ans) => {
      const a = ans.trim().toLowerCase();
      if (!a) resolve(defaultYes);
      else resolve(a === 'y' || a === 'yes');
    });
  });
}

// ── File helpers ──────────────────────────────────────────────────────────────
function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

function writeFileSafe(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
}

function readFileSafe(filePath, fallback = '') {
  try { return fs.readFileSync(filePath, 'utf8'); } catch { return fallback; }
}

function backupFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const backupPath = `${filePath}.shonin-backup-${Date.now()}`;
  fs.copyFileSync(filePath, backupPath);
  info(`Backed up ${filePath} to ${backupPath}`);
}

function appendIfMissing(filePath, marker, block) {
  const content = readFileSafe(filePath);
  if (content.includes(marker)) {
    info(`${filePath} already has Shonin config — skipping`);
    return false;
  }
  fs.appendFileSync(filePath, '\n' + block + '\n', 'utf8');
  return true;
}

// ── Hook script content ───────────────────────────────────────────────────────
const HOOK_SCRIPT = `#!/bin/bash
# Shonin approval hook
# Usage: shonin-approve.sh "COMMAND" "WHY"
# Generated by npx shonin-setup

COMMAND="$1"
WHY="$2"
CWD=$(pwd)
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")

API_KEY="\${SHONIN_API_KEY:-}"
API_URL="\${SHONIN_API_URL:-https://shonin.dev/api/v1}"
APPROVER="\${SHONIN_APPROVER:-}"

if [ -z "$API_KEY" ]; then
  echo "SHONIN_API_KEY is not set. Set it in your shell profile or .env"
  exit 1
fi
if [ -z "$APPROVER" ]; then
  echo "SHONIN_APPROVER is not set. Set it in your shell profile or .env"
  exit 1
fi

# ── Classify command type ──────────────────────────────────────────────────────
classify_command() {
  local cmd="$1"
  local lower
  lower=$(echo "$cmd" | tr '[:upper:]' '[:lower:]')

  if echo "$lower" | grep -q "push" && echo "$lower" | grep -qE "( -f| --force|--force-with-lease)"; then
    echo "git_push_force"
  elif echo "$lower" | grep -q "reset" && echo "$lower" | grep -q "\\-\\-hard"; then
    echo "git_reset_hard"
  elif echo "$lower" | grep -qE "^rm "; then
    echo "rm"
  elif echo "$lower" | grep -qi "drop table"; then
    echo "sql_drop"
  elif echo "$lower" | grep -qiE "(migrat|migration)"; then
    echo "sql_migration"
  elif echo "$lower" | grep -q "push"; then
    echo "git_push"
  elif echo "$lower" | grep -q "commit"; then
    echo "git_commit"
  else
    echo "unknown"
  fi
}

COMMAND_TYPE=$(classify_command "$COMMAND")

# ── Gather git enrichment (5s timeout each) ────────────────────────────────────
FILES_JSON="[]"
DIFF_CONTENT=""

if git rev-parse --is-inside-work-tree &>/dev/null; then
  RAW_FILES=$(timeout 5 git diff --name-status HEAD 2>/dev/null || echo "")
  if [ -n "$RAW_FILES" ]; then
    FILES_JSON=$(echo "$RAW_FILES" | python3 -c "
import sys, json
rows = []
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    parts = line.split(chr(9), 1)
    if len(parts) < 2:
        continue
    code, path = parts[0][0], parts[1]
    status_map = {'M': 'modified', 'A': 'added', 'D': 'deleted', 'R': 'renamed'}
    status = status_map.get(code, 'modified')
    rows.append({'path': path, 'status': status})
print(json.dumps(rows))
" 2>/dev/null || echo "[]")
  fi

  if [ "$COMMAND_TYPE" = "rm" ]; then
    RM_TARGET=$(echo "$COMMAND" | sed 's/^rm[[:space:]]*//')
    FILES_JSON=$(python3 -c "import json; print(json.dumps([{'path': '$RM_TARGET', 'status': 'deleted'}]))" 2>/dev/null || echo "[]")
  fi

  # A diff contains your code, so it is only sent (and stored and emailed) when you opt in with SHONIN_SEND_DIFF=1.
  if [ "\${SHONIN_SEND_DIFF:-0}" = "1" ]; then
    DIFF_CONTENT=$(timeout 5 git diff HEAD 2>/dev/null | head -c 51200 || echo "")
  fi
fi

echo "Requesting Shonin approval for: $COMMAND"

export COMMAND WHY COMMAND_TYPE FILES_JSON DIFF_CONTENT APPROVER

RESPONSE=$(python3 -c "
import json, os, sys

command_type = os.environ.get('COMMAND_TYPE', 'unknown')
files_json = os.environ.get('FILES_JSON', '[]')
diff = os.environ.get('DIFF_CONTENT', '')

try:
    files = json.loads(files_json)
except Exception:
    files = []

payload = {
    'action': os.environ.get('COMMAND', ''),
    'approver_email': os.environ.get('APPROVER', ''),
    'context': os.environ.get('WHY', ''),
    'command_type': command_type if command_type != 'unknown' else None,
}

if files:
    payload['files'] = files
if diff:
    payload['diff'] = diff

payload = {k: v for k, v in payload.items() if v is not None}
print(json.dumps(payload))
" | curl -s -X POST "$API_URL/approvals" \\
    -H "Authorization: Bearer $API_KEY" \\
    -H "Content-Type: application/json" \\
    -d @-)

APPROVAL_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])" 2>/dev/null)

if [ -z "$APPROVAL_ID" ]; then
  echo "Failed to create approval. Response: $RESPONSE"
  exit 1
fi

echo "Email sent to $APPROVER. Waiting for your decision..."

for i in $(seq 1 60); do
  sleep 10
  STATUS=$(curl -s "$API_URL/approvals/$APPROVAL_ID" \\
    -H "Authorization: Bearer $API_KEY" | \\
    python3 -c "import sys,json; print(json.load(sys.stdin)['status'])" 2>/dev/null)

  if [ "$STATUS" = "approved" ]; then
    echo "Approved. Proceeding."
    exit 0
  elif [ "$STATUS" = "rejected" ]; then
    echo "Rejected. Stopping."
    exit 1
  fi
  echo "Still pending... ($((i*10))s elapsed)"
done

echo "Timed out after 10 minutes."
exit 1
`;

// ── gstack AskUserQuestion hook script ───────────────────────────────────────
const GSTACK_HOOK_SCRIPT = `#!/bin/bash
# Shonin AskUserQuestion hook for Claude Code / gstack
# Intercepts AskUserQuestion tool calls and routes them through Shonin
# Generated by npx shonin-setup

API_KEY="\${SHONIN_API_KEY:-}"
API_URL="\${SHONIN_API_URL:-https://shonin.dev/api/v1}"
RESPONDENT="\${SHONIN_APPROVER:-}"

if [ -z "$API_KEY" ] || [ -z "$RESPONDENT" ]; then
  # Fall through to terminal if not configured
  exit 0
fi

# Read hook input from stdin (Claude Code passes tool input as JSON)
INPUT=$(cat)

QUESTION=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('question',''))" 2>/dev/null)
OPTIONS_RAW=$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
opts = d.get('options', [])
result = []
for i, opt in enumerate(opts):
    label = chr(65+i) + ') ' + str(opt)
    result.append({'key': chr(65+i), 'label': label})
print(json.dumps(result))
" 2>/dev/null || echo "[]")

if [ -z "$QUESTION" ]; then
  exit 0
fi

PAYLOAD=$(python3 -c "
import json, sys
payload = {
    'question': '$QUESTION'.replace(\"'\", \"'\\\\''\"),
    'options': $OPTIONS_RAW,
    'respondent_email': '$RESPONDENT',
    'expires_in_hours': 2
}
print(json.dumps(payload))
")

RESPONSE=$(echo "$PAYLOAD" | curl -s -X POST "$API_URL/decisions" \\
    -H "Authorization: Bearer $API_KEY" \\
    -H "Content-Type: application/json" \\
    -d @-)

DECISION_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])" 2>/dev/null)

if [ -z "$DECISION_ID" ]; then
  # Fall through to terminal
  exit 0
fi

echo "Shonin: Decision email sent to $RESPONDENT for: $QUESTION"
echo "Waiting for email response..."

for i in $(seq 1 24); do
  sleep 5
  RESULT=$(curl -s "$API_URL/decisions/$DECISION_ID" \\
    -H "Authorization: Bearer $API_KEY")
  STATUS=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)['status'])" 2>/dev/null)

  if [ "$STATUS" = "decided" ]; then
    CHOSEN=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('chosen_key',''))" 2>/dev/null)
    echo "Answer received: $CHOSEN"
    # Output for Claude Code to use as context
    echo "USER_CHOSE: $CHOSEN"
    exit 0
  fi
done

echo "Decision timed out — falling back to terminal prompt."
exit 0
`;

// ── Claude Code settings helpers ──────────────────────────────────────────────
function readSettings(settingsPath) {
  try {
    const raw = readFileSafe(settingsPath, '{}');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

function writeSettings(settingsPath, obj) {
  writeFileSafe(settingsPath, JSON.stringify(obj, null, 2) + '\n');
}

function addBashHook(settings) {
  if (!settings.hooks) settings.hooks = {};
  if (!settings.hooks.PreToolUse) settings.hooks.PreToolUse = [];

  const hooks = settings.hooks.PreToolUse;
  const existing = hooks.find((h) => h.matcher === 'Bash');

  const hookCmd = {
    type: 'command',
    command: 'bash ~/shonin-approve.sh "$TOOL_INPUT" "auto-approval check"',
  };

  if (existing) {
    if (!existing.hooks) existing.hooks = [];
    const alreadyHas = existing.hooks.some((h) => h.command && h.command.includes('shonin-approve'));
    if (!alreadyHas) existing.hooks.push(hookCmd);
  } else {
    hooks.push({ matcher: 'Bash', hooks: [hookCmd] });
  }
  return settings;
}

function addAskUserQuestionHook(settings) {
  if (!settings.hooks) settings.hooks = {};
  if (!settings.hooks.PreToolUse) settings.hooks.PreToolUse = [];

  const hooks = settings.hooks.PreToolUse;
  const existing = hooks.find((h) => h.matcher === 'AskUserQuestion');

  const hookCmd = {
    type: 'command',
    command: 'bash ~/shonin-decision-hook.sh',
  };

  if (existing) {
    if (!existing.hooks) existing.hooks = [];
    const alreadyHas = existing.hooks.some((h) => h.command && h.command.includes('shonin-decision'));
    if (!alreadyHas) existing.hooks.push(hookCmd);
  } else {
    hooks.push({ matcher: 'AskUserQuestion', hooks: [hookCmd] });
  }
  return settings;
}

// ── CLAUDE.md block ────────────────────────────────────────────────────────────
const CLAUDE_MD_BLOCK = `
## Human Approval via Shonin

### Automatic hooks
Git, rm, and database commands are automatically intercepted
and routed through Shonin for email approval. You do not need
to call the script manually for these.

### Manual approval required
For ALL of these situations, call the approval script BEFORE
presenting options or proceeding:

1. Any time you would ask "Shall I proceed?"
2. Any time you present numbered options (1, 2, 3)
3. Any time you ask the user to choose between approaches
4. Any time you are uncertain about scope of changes

How to call it:
\`\`\`bash
~/shonin-approve.sh "WHAT YOU ARE ABOUT TO DO" "WHY AND WHAT HAPPENS NEXT"
\`\`\`

Wait for exit code:
- 0 = approved, proceed
- 1 = rejected or timeout, STOP and tell the user

### Never proceed without approval on:
- git push (any branch)
- git commit
- git merge
- rm or rmdir
- Any SQL migration
- Any .env file changes
- Any production config changes
- Any --force flag
`;

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n' + '═'.repeat(60));
  console.log(`  ${C.bold}${C.cyan}Shonin Setup${C.reset}  — Human approval for AI agents`);
  console.log('═'.repeat(60) + '\n');
  console.log('  This wizard configures Shonin for Claude Code in ~2 minutes.\n');

  // ── Step 1: Credentials ───────────────────────────────────────────────────
  step('Step 1/4  Credentials');
  console.log('  Get your API key at https://shonin.dev\n');

  const apiKey = await ask('Shonin API key');
  if (!apiKey) { err('API key is required'); process.exit(1); }

  const approverEmail = await ask('Your email address (for approval notifications)');
  if (!approverEmail || !approverEmail.includes('@')) {
    err('A valid email address is required');
    process.exit(1);
  }

  // ── Step 2: Hook script ───────────────────────────────────────────────────
  step('Step 2/4  Hook script');
  const hookPath = path.join(os.homedir(), 'shonin-approve.sh');
  const overwrite = fs.existsSync(hookPath) ? await askYN(`${hookPath} already exists — overwrite?`, false) : true;

  if (overwrite) {
    writeFileSafe(hookPath, HOOK_SCRIPT);
    fs.chmodSync(hookPath, 0o755);
    ok(`Wrote ${hookPath}`);
  } else {
    info(`Keeping existing ${hookPath}`);
  }

  // ── Step 3: gstack AskUserQuestion hook (optional) ────────────────────────
  step('Step 3/4  gstack / AskUserQuestion routing (optional)');
  console.log('  Routes Claude\'s "AskUserQuestion" calls to your email instead of terminal.\n');

  const setupGstack = await askYN('Set up email routing for AskUserQuestion (recommended for async work)?', true);
  if (setupGstack) {
    const gstackHookPath = path.join(os.homedir(), 'shonin-decision-hook.sh');
    const overwriteGstack = fs.existsSync(gstackHookPath)
      ? await askYN(`${gstackHookPath} already exists — overwrite?`, false)
      : true;

    if (overwriteGstack) {
      writeFileSafe(gstackHookPath, GSTACK_HOOK_SCRIPT);
      fs.chmodSync(gstackHookPath, 0o755);
      ok(`Wrote ${gstackHookPath}`);
    }
  }

  // ── Step 4: Claude Code config ────────────────────────────────────────────
  step('Step 4/4  Claude Code config');

  const claudeDir = path.join(os.homedir(), '.claude');
  const claudeMdPath = path.join(claudeDir, 'CLAUDE.md');
  const settingsPath = path.join(claudeDir, 'settings.json');

  // CLAUDE.md
  if (!readFileSafe(claudeMdPath).includes('## Human Approval via Shonin')) backupFile(claudeMdPath);
  const addedClaudeMd = appendIfMissing(claudeMdPath, '## Human Approval via Shonin', CLAUDE_MD_BLOCK);
  if (addedClaudeMd) ok(`Updated ${claudeMdPath}`);

  // settings.json hooks
  backupFile(settingsPath);
  let settings = readSettings(settingsPath);
  settings = addBashHook(settings);
  if (setupGstack) settings = addAskUserQuestionHook(settings);
  writeSettings(settingsPath, settings);
  ok(`Updated ${settingsPath}`);

  // Shell env vars
  const shell = process.env.SHELL || '';
  const rcFile = shell.includes('zsh')
    ? path.join(os.homedir(), '.zshrc')
    : path.join(os.homedir(), '.bashrc');

  const envBlock = `
# Shonin — human approval for AI agents
export SHONIN_API_KEY="${apiKey}"
export SHONIN_APPROVER="${approverEmail}"
export SHONIN_API_URL="https://shonin.dev/api/v1"
# export SHONIN_SEND_DIFF=1   # also send git diffs with approval requests (your code is stored and emailed)
`;

  if (!readFileSafe(rcFile).includes('# Shonin')) backupFile(rcFile);
  const addedEnv = appendIfMissing(rcFile, '# Shonin', envBlock);
  if (addedEnv) ok(`Added env vars to ${rcFile}`);

  // ── Done ──────────────────────────────────────────────────────────────────
  console.log('\n' + '═'.repeat(60));
  console.log(`  ${C.bold}${C.green}Setup complete!${C.reset}`);
  console.log('═'.repeat(60));
  console.log(`
  ${C.bold}Next steps:${C.reset}

  1. Reload your shell:
     ${C.cyan}source ${rcFile}${C.reset}

  2. Test it:
     ${C.cyan}~/shonin-approve.sh "git push origin main" "Testing Shonin"${C.reset}

  3. You should receive an approval email at ${C.bold}${approverEmail}${C.reset}.

  ${C.dim}Restart Claude Code for the hooks to take effect.${C.reset}
`);

  rl.close();
}

main().catch((e) => {
  err(e.message || String(e));
  rl.close();
  process.exit(1);
});
